// <auto-generated />
using FileExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileExplorer.Migrations.ContextoBDMigrations
{
    [DbContext(typeof(ContextoBD))]
    partial class ContextoBDModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileExplorer.Models.FileNode", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Path");

                    b.ToTable("FileNodes");

                    b.HasData(
                        new
                        {
                            Path = "/UABC",
                            IsDirectory = true,
                            IsExpanded = true,
                            Name = "UABC"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada",
                            IsDirectory = true,
                            IsExpanded = true,
                            Name = "Ensenada"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Artes",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Facultad de Artes"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Artes/Artes Visuales",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Artes Visuales"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Artes/Artes Musicales",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Artes Musicales"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Artes/Artes Teatrales",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Artes Teatrales"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Artes/Artes Literarias",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Artes Literarias"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Facultad de Ciencias"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias/Biologia",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Biologia"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias/Matematicas",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Matematicas"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias/Fisica",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Fisica"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias/Quimica",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Quimica"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias Marinas",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Facultad de Ciencias Marinas"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias Marinas/Biologia Marina",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Biologia Marina"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias Marinas/Oceanografia",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Oceanografia"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias Marinas/Ciencias del Mar",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Ciencias del Mar"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias Marinas/Ingenieria en Ciencias del Mar",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Ingenieria en Ciencias del Mar"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ciencias Marinas/Ingenieria en Transporte Maritimo",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Ingenieria en Transporte Maritimo"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Deportes",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Facultad de Deportes"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Deportes/Ciencias del Deporte",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Ciencias del Deporte"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Deportes/Entrenamiento Deportivo",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Entrenamiento Deportivo"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Deportes/Rehabilitacion y Terapia Fisica",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Rehabilitacion y Terapia Fisica"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Deportes/Nutricion y Dietetica",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Nutricion y Dietetica"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Deportes/Educacion Fisica",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Educacion Fisica"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ingenieria",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Facultad de Ingenieria"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ingenieria/Tronco Comun de Ingenieria",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Tronco Comun de Ingenieria"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ingenieria/Ingenieria Civil",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Ingenieria Civil"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ingenieria/Ingenieria en Electronica",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Ingenieria en Electronica"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ingenieria/Ingenieria en Computacion",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Ingenieria en Computacion"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ingenieria/Ingenieria Industrial",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Ingenieria Industrial"
                        },
                        new
                        {
                            Path = "/UABC/Ensenada/Facultad de Ingenieria/Bioingenieria",
                            IsDirectory = true,
                            IsExpanded = false,
                            Name = "Bioingenieria"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
